#!/usr/bin/env node
/**
 * Bakes the current build's version metadata into
 * `src/app/core/version.ts` so the app can show it in the footer.
 *
 * Run from `deploy.sh` BEFORE `ng build` (so the file is committed
 * into the bundle Angular compiles). Run before `publish-update.mjs`
 * too so `bundle.version` here matches the `version` in the
 * Capacitor live-update manifest.
 *
 * Version anatomy:
 *   display     — human-readable, shown in the footer (e.g. "2026.05.21 · 14:42")
 *   bundle      — semver-compatible, monotonic in time, matches the
 *                 live-update manifest ("26.141.882")
 *   buildDate   — ISO timestamp of when this script ran
 *   commitHash  — short git SHA for diagnostics
 *
 * The bundle is TIME-based, not git-commit-count-based. Format is
 * "YY.DOY.MOD" where:
 *   YY  = years since 2000 (e.g. 26 for 2026)
 *   DOY = day-of-year UTC (1..366)
 *   MOD = minutes-of-day UTC (0..1439)
 *
 * Strictly monotonic forwards in real time. Never regresses just
 * because main was reset to an earlier commit; never collides with
 * a different branch's commit count. The Capacitor live-updater
 * uses semver compare on these strings, so a newer build always
 * sorts strictly above any older build.
 */

import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const uiRoot = path.resolve(__dirname, '..');
const outPath = path.join(uiRoot, 'src', 'app', 'core', 'version.ts');

function sh(cmd) {
  return execSync(cmd, { cwd: uiRoot, encoding: 'utf8' }).trim();
}

function dayOfYearUTC(d) {
  const start = Date.UTC(d.getUTCFullYear(), 0, 1);
  return Math.floor((d.getTime() - start) / 86400000) + 1;
}

function main() {
  const commitHash = sh('git rev-parse --short=7 HEAD');
  const now = new Date();
  const yy = now.getUTCFullYear() - 2000;
  const doy = dayOfYearUTC(now);
  const mod = now.getUTCHours() * 60 + now.getUTCMinutes();

  const bundle = `${yy}.${doy}.${mod}`;

  // Display uses the local date and a HH:MM stamp so it's readable
  // at a glance. The bundle id is the canonical sortable value.
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const mm = String(now.getMinutes()).padStart(2, '0');
  const display = `${y}.${m}.${d} · ${hh}:${mm}`;

  const contents =
    `// AUTO-GENERATED by scripts/write-version.mjs. Do not edit by hand;\n` +
    `// edits will be overwritten on the next deploy. See deploy.sh.\n` +
    `\n` +
    `export const VERSION = {\n` +
    `  display: '${display}',\n` +
    `  bundle: '${bundle}',\n` +
    `  buildDate: '${now.toISOString()}',\n` +
    `  commitHash: '${commitHash}',\n` +
    `} as const;\n`;

  fs.writeFileSync(outPath, contents);
  console.log(`[write-version] wrote ${path.relative(uiRoot, outPath)}: ${display} (${bundle})`);
}

main();
