#!/usr/bin/env node
/**
 * Bakes the current build's version metadata into
 * `src/app/core/version.ts` so the app can show it in the footer.
 *
 * Run from `deploy.sh` BEFORE `ng build` (so the file is committed
 * into the bundle Angular compiles). Run before `publish-update.mjs`
 * too so `bundle.version` here matches the `version` in the
 * Capacitor live-update manifest.
 *
 * Versioning scheme (introduced 2026-05-24):
 *   - Stored in package.json as the canonical "version" field.
 *   - This script bumps the PATCH on every invocation and writes
 *     the new version back to package.json AND to version.ts.
 *   - Format: "MAJOR.MINOR.PATCH" — plain semver. The UI footer
 *     renders it as "v.MAJOR.MINOR.PATCH".
 *
 * Bumping the MAJOR or MINOR is a manual edit of package.json
 * between deploys when there's a meaningful release boundary.
 *
 * Version anatomy in version.ts:
 *   display     — "v.MAJOR.MINOR.PATCH"
 *   bundle      — "MAJOR.MINOR.PATCH" (semver-compatible, what the
 *                 live-update manifest sees)
 *   buildDate   — ISO timestamp of when this script ran
 *   commitHash  — short git SHA for diagnostics
 */
import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const uiRoot = path.resolve(__dirname, '..');
const outPath = path.join(uiRoot, 'src', 'app', 'core', 'version.ts');
const pkgPath = path.join(uiRoot, 'package.json');

function sh(cmd) {
  return execSync(cmd, { cwd: uiRoot, encoding: 'utf8' }).trim();
}

function main() {
  // Read current version from package.json.
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const current = pkg.version ?? '0.1.0';
  const parts = current.split('.').map((s) => Number(s));
  if (parts.length !== 3 || parts.some((n) => Number.isNaN(n))) {
    throw new Error(`package.json version "${current}" is not MAJOR.MINOR.PATCH`);
  }
  // Bump patch.
  parts[2] += 1;
  const bundle = parts.join('.');

  // Write back to package.json.
  pkg.version = bundle;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

  const commitHash = sh('git rev-parse --short=7 HEAD');
  const now = new Date();
  const display = `v.${bundle}`;

  const contents =
    `// AUTO-GENERATED by scripts/write-version.mjs. Do not edit by hand;\n` +
    `// edits will be overwritten on the next deploy. See deploy.sh.\n` +
    `\n` +
    `export const VERSION = {\n` +
    `  display: '${display}',\n` +
    `  bundle: '${bundle}',\n` +
    `  buildDate: '${now.toISOString()}',\n` +
    `  commitHash: '${commitHash}',\n` +
    `} as const;\n`;

  fs.writeFileSync(outPath, contents);
  console.log(`[write-version] bumped ${current} -> ${bundle}; wrote package.json + ${path.relative(uiRoot, outPath)}`);
}

main();
