#!/usr/bin/env node
/**
 * Bakes the current build's version metadata into
 * `src/app/core/version.ts` so the app can show it in the footer.
 *
 * Run from `deploy.sh` BEFORE `ng build` (so the file is committed
 * into the bundle Angular compiles). Run before `publish-update.mjs`
 * too so `bundle.version` here matches the `version` in the
 * Capacitor live-update manifest.
 *
 * Version anatomy:
 *   display     — human-readable, shown in the footer (e.g. "2026.05.17 · b109")
 *   bundle      — semver-compatible, matches the live-update manifest ("0.0.109")
 *   buildDate   — ISO timestamp of when this script ran
 *   commitHash  — short git SHA for diagnostics
 */

import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const uiRoot = path.resolve(__dirname, '..');
const outPath = path.join(uiRoot, 'src', 'app', 'core', 'version.ts');

function sh(cmd) {
  return execSync(cmd, { cwd: uiRoot, encoding: 'utf8' }).trim();
}

function main() {
  const commitCount = sh('git rev-list --count HEAD');
  const commitHash = sh('git rev-parse --short=7 HEAD');
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  const dateStr = `${y}.${m}.${d}`;
  const display = `${dateStr} · b${commitCount}`;
  // Bundle major bumped from 0.0 to 0.1 on 2026-05-21 after main was
  // reset to a pre-voice commit. The previous 0.0.132 (on the
  // speech-experimental branch) was higher than the post-reset
  // commit count of 0.0.123, which would have blocked live-update
  // distribution. Bumping the major makes the post-reset builds sort
  // higher than anything on speech-experimental, so installed APKs
  // pick up the new persona work cleanly via the live-update flow.
  const bundle = `0.1.${commitCount}`;

  const contents =
    `// AUTO-GENERATED by scripts/write-version.mjs. Do not edit by hand;\n` +
    `// edits will be overwritten on the next deploy. See deploy.sh.\n` +
    `\n` +
    `export const VERSION = {\n` +
    `  display: '${display}',\n` +
    `  bundle: '${bundle}',\n` +
    `  buildDate: '${now.toISOString()}',\n` +
    `  commitHash: '${commitHash}',\n` +
    `} as const;\n`;

  fs.writeFileSync(outPath, contents);
  console.log(`[write-version] wrote ${path.relative(uiRoot, outPath)}: ${display} (${bundle})`);
}

main();
